language: cpp
compiler:
  # - gcc
  - clang

before_install:
  # Get GCC 4.9.2 (too memory intensive so currently deactivated)
  - if [ "$CXX" == "g++" ]; then wget https://github.com/Viq111/travis-container-packets/releases/download/gcc-4.9.2/gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then tar -xjf gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then rm gcc.tar.bz2; fi
  - if [ "$CXX" == "g++" ]; then export PATH=$(pwd)/gcc/bin:$PATH; fi
  - if [ "$CXX" == "g++" ]; then export LIBRARY_PATH=$(pwd)/gcc/lib64:$LIBRARY_PATH; fi
  - if [ "$CXX" == "g++" ]; then export LD_LIBRARY_PATH=$(pwd)/gcc/lib64:$LD_LIBRARY_PATH; fi
  - if [ "$CXX" == "g++" ]; then export CPLUS_INCLUDE_PATH=$(pwd)/gcc/include/c++/4.9.2:$CPLUS_INCLUDE_PATH; fi

  # Get clang 3.4 (http://gotoanswer.stanford.edu/?q=Travis+CI+with+Clang+3.4+and+C%2B%2B11)
  # necessary as the VM clang links tp old libstdc++
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq update; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq install libstdc++-4.8-dev clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - if [ "$CXX" == "clang++" ]; then export CC= "clang++-3.4"; fi

  # Get CMake 3.1
  - wget https://github.com/Viq111/travis-container-packets/releases/download/cmake-3.1.2/cmake.tar.bz2
  - tar -xjf cmake.tar.bz2
  - rm cmake.tar.bz2
  - export PATH=$(pwd)/cmake/bin:$PATH
  - sudo apt-get install python-pip
  - sudo pip install numpy
  - sudo pip install matplotlib

install:
  # Get boost
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost

script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_PYGMO="ON" -DBUILD_EXAMPLES="ON" -DENABLE_TESTS="ON" -DPYTHON_MODULES_DIR="~/local/python" -DCMAKE_INSTALL_PREFIX="~/local"
  - make -j4
  - make test
  - make install
  - export PYTHONPATH=~/local/python
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/local/lib:${PWD%/build}/boost/lib
  - python -c "from PyGMO import test; test.run_full_test_suite()"

after_success:
  - python -c "import PyGMO; print(PyGMO.__version__)"
